; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_song_1

@sfx_ntsc_song_1:
	.byte $87,$4c,$88,$00,$86,$87,$89,$f0,$01,$87,$61,$01,$87,$77,$01,$87
	.byte $9c,$01,$87,$36,$01,$87,$43,$01,$87,$52,$01,$87,$6a,$01,$87,$84
	.byte $01,$87,$8e,$01,$87,$2c,$01,$87,$34,$01,$87,$3f,$01,$87,$51,$01
	.byte $87,$64,$01,$00

.export sounds
