; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_song_1

@sfx_ntsc_song_1:
	.byte $8a,$0c,$01,$89,$3d,$01,$89,$3f,$01,$89,$37,$01,$8a,$0b,$89,$30
	.byte $01,$89,$3d,$01,$89,$3f,$01,$89,$37,$01,$89,$34,$01,$00

.export sounds
