; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_song_1

@sfx_ntsc_song_1:
	.byte $89,$f0,$01,$8a,$0e,$89,$33,$01,$89,$36,$01,$89,$3a,$01,$89,$3b
	.byte $01,$89,$3a,$02,$89,$39,$01,$89,$37,$01,$89,$36,$01,$89,$35,$03
	.byte $89,$36,$01,$89,$34,$04,$89,$33,$02,$89,$32,$01,$00

.export sounds
