; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_song_1

@sfx_ntsc_song_1:
	.byte $8a,$01,$89,$37,$01,$89,$3a,$01,$89,$3c,$01,$89,$3a,$01,$89,$37
	.byte $01,$89,$36,$01,$89,$35,$01,$89,$33,$01,$89,$32,$01,$89,$31,$01
	.byte $00

.export sounds
