; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_song_1

@sfx_ntsc_song_1:
	.byte $87,$d5,$88,$00,$86,$8f,$89,$f0,$01,$87,$c9,$01,$87,$b3,$01,$86
	.byte $80,$01,$87,$8e,$86,$8f,$01,$00

.export sounds
